### ISSUE TITLE
I have an issue with AmazonS3Client

### ISSUE THREAD

**Issue by da-demo-account** [dagnir/aws-sdk-java#19]
S3 client is failing to upload certain files

**Comment by dagnir** [comment]
Hi can yo please provide some details about the failure?

**Comment by dagnir** [comment]
This is a reply

**Comment by dagnir** [comment]
This is another reply (shouldn't remove the waiting-reply label)

**Comment by da-demo-account** [comment]
Yes, the details are...

**Comment by dagnir** [comment]
Cool. Can you try these steps?
